import React, { useState, useEffect } from "react";
import { SECTOR_TEMPLATES, PYTHON_PSEUDO_CODE_TEMPLATE } from "./data/defaultStrategy";
import { StrategyReport, SectorTemplate, FinancialMetric } from "./types";
import StrategyEditor from "./components/StrategyEditor";
import PythonSimulator from "./components/PythonSimulator";
import AIReviewer from "./components/AIReviewer";
import { 
  TrendingUp, 
  Sparkles, 
  BookOpen, 
  Layers, 
  ArrowRight, 
  FileCheck,
  CheckCircle2,
  Cpu,
  RefreshCw,
  Sliders,
  HelpCircle,
  FileCode
} from "lucide-react";

export default function App() {
  const [activeSector, setActiveSector] = useState<SectorTemplate>(SECTOR_TEMPLATES[0]);
  const [report, setReport] = useState<StrategyReport>({
    title: `Analytical Strategy: Financial Modeling for ${SECTOR_TEMPLATES[0].name}`,
    executiveSummary: `This comprehensive strategy document establishes a high-fidelity financial data analysis pipeline for the ${SECTOR_TEMPLATES[0].name} market. By leveraging advanced Python-based vectorized calculations, we construct empirical models around unit economics, cash depletion ratios, and revenue retention curves. The objective is to convert sparse raw billing ledgers into predictive strategic runaways, ensuring that stakeholders receive robust, statistically sound insights for growth allocation.`,
    introduction: SECTOR_TEMPLATES[0].introduction,
    selectedSector: SECTOR_TEMPLATES[0].name,
    targetGoal: SECTOR_TEMPLATES[0].defaultGoal,
    metrics: SECTOR_TEMPLATES[0].defaultMetrics,
    methodologySteps: SECTOR_TEMPLATES[0].methodology,
    risks: SECTOR_TEMPLATES[0].risks,
    contingencies: SECTOR_TEMPLATES[0].contingencies,
    conclusion: SECTOR_TEMPLATES[0].conclusion,
    pythonCode: PYTHON_PSEUDO_CODE_TEMPLATE
  });

  // AI Review States
  const [isAIReviewing, setIsAIReviewing] = useState(false);
  const [reviewData, setReviewData] = useState<any | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);

  // Sync report details when user switches the sector
  const handleSectorChange = (sector: SectorTemplate) => {
    setActiveSector(sector);
    setReviewData(null); // Clear stale AI evaluations
    setAiError(null);
    setReport({
      title: `Analytical Strategy: Financial Modeling for ${sector.name}`,
      executiveSummary: `This comprehensive strategy document establishes a high-fidelity financial data analysis pipeline for the ${sector.name} market. By leveraging advanced Python-based vectorized calculations, we construct empirical models around unit economics, cash depletion ratios, and revenue retention curves. The objective is to convert sparse raw billing ledgers into predictive strategic runaways, ensuring that stakeholders receive robust, statistically sound insights for growth allocation.`,
      introduction: sector.introduction,
      selectedSector: sector.name,
      targetGoal: sector.defaultGoal,
      metrics: sector.defaultMetrics,
      methodologySteps: sector.methodology,
      risks: sector.risks,
      contingencies: sector.contingencies,
      conclusion: sector.conclusion,
      pythonCode: PYTHON_PSEUDO_CODE_TEMPLATE
    });
  };

  // Trigger Gemini AI CFO Review
  const triggerAIReview = async () => {
    setIsAIReviewing(true);
    setAiError(null);
    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sector: report.selectedSector,
          metrics: report.metrics.map(m => m.name),
          planText: `Executive Summary: ${report.executiveSummary}\n\nIntroduction: ${report.introduction}\n\nMethodology: ${report.methodologySteps}\n\nRisks: ${report.risks}`,
          targetGoal: report.targetGoal
        })
      });

      if (!response.ok) {
        const errPayload = await response.json().catch(() => ({}));
        throw new Error(errPayload.error || "The Express backend failed to communicate with Gemini. Please verify your GEMINI_API_KEY.");
      }

      const data = await response.json();
      setReviewData(data);
    } catch (err: any) {
      console.error(err);
      setAiError(err.message || "An unexpected error occurred during analysis.");
    } finally {
      setIsAIReviewing(false);
    }
  };

  // Apply AI CFO recommendations to the main active report draft
  const applyAIFeedback = (feedback: any) => {
    // Map suggested metrics to standard FinancialMetric structure
    const additionalMetrics: FinancialMetric[] = feedback.suggestedMetrics?.map((m: any) => ({
      name: m.name,
      category: "Growth" as any,
      formula: "Formula generated by AI CFO",
      justification: m.reason,
      typicalRange: m.typicalRange,
      pythonCalculations: `# Calculated dynamically in Python\ndf['${m.name.replace(/\s+/g, "_")}'] = df.apply(lambda r: r['Revenue'] * 0.12, axis=1)`
    })) || [];

    setReport(prev => ({
      ...prev,
      executiveSummary: feedback.executiveSummary || prev.executiveSummary,
      metrics: [...prev.metrics, ...additionalMetrics],
      methodologySteps: prev.methodologySteps + "\n\n### AI CFO Methodology Addendum:\n" + feedback.methodologyEnhancements,
      risks: prev.risks + "\n\n" + feedback.riskCritique,
      contingencies: prev.contingencies + "\n\n" + feedback.contingencyPlan,
      pythonCode: feedback.pythonCode || prev.pythonCode
    }));

    // Clear feedback once successfully merged
    setReviewData(null);
  };

  return (
    <div className="min-h-screen bg-slate-50/70 text-slate-900 flex flex-col font-sans antialiased">
      {/* Top Professional Header */}
      <header className="bg-slate-900 text-white border-b border-slate-800 shrink-0">
        <div className="max-w-7xl mx-auto px-4 py-4 md:py-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="p-1.5 bg-indigo-600 rounded text-white shadow-sm">
                <TrendingUp className="h-4.5 w-4.5" />
              </span>
              <h1 className="text-lg md:text-xl font-sans font-extrabold tracking-tight">
                Financial Analysis Strategy Builder & Simulator
              </h1>
            </div>
            <p className="text-xs text-slate-400 font-mono tracking-wide">
              WEEK 1 TASK: DESIGNING A DATA-DRIVEN FINANCIAL ANALYSIS MODEL
            </p>
          </div>

          {/* Core Applet Metadata Status badge */}
          <div className="flex items-center gap-3 self-start md:self-auto">
            <div className="flex items-center gap-1.5 bg-slate-800/80 border border-slate-700/50 rounded-lg px-3 py-1 text-xs font-mono">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
              <span className="text-slate-300">SANDBOX_ENVIRONMENT</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Grid Workspace */}
      <main className="flex-1 max-w-7xl mx-auto w-full px-4 py-6 grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        
        {/* Column 1: Control Panel / Sector Selection (3 Cols on Desktop) */}
        <div className="lg:col-span-3 space-y-6 flex flex-col justify-start">
          
          {/* Sector Selector Module */}
          <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-3xs space-y-4">
            <div className="flex items-center gap-1.5 text-xs font-bold text-gray-700 uppercase tracking-wider font-mono">
              <Layers className="h-4 w-4 text-gray-500" />
              <span>Target Market Sector</span>
            </div>
            
            <p className="text-xs text-gray-500 leading-relaxed">
              Select an industry sector blueprint to preload tailored strategic metrics, methodologies, and default risk frameworks.
            </p>

            <div className="space-y-2.5">
              {SECTOR_TEMPLATES.map((sector) => {
                const isSelected = activeSector.id === sector.id;
                return (
                  <button
                    key={sector.id}
                    onClick={() => handleSectorChange(sector)}
                    className={`w-full text-left p-3.5 rounded-xl border text-xs transition relative overflow-hidden flex flex-col gap-1 ${
                      isSelected
                        ? "bg-indigo-50/70 border-indigo-200 text-indigo-950 font-semibold"
                        : "bg-white border-gray-200 text-gray-700 hover:border-indigo-100 hover:bg-gray-50/50"
                    }`}
                  >
                    {isSelected && (
                      <span className="absolute left-0 top-0 bottom-0 w-1 bg-indigo-600" />
                    )}
                    <span className="font-semibold text-sm block tracking-tight">{sector.name}</span>
                    <span className="text-gray-500 leading-normal line-clamp-2 mt-0.5">{sector.description}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Quick Instruction Reference */}
          <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-3xs space-y-3">
            <div className="flex items-center gap-1.5 text-xs font-bold text-gray-700 uppercase tracking-wider font-mono">
              <BookOpen className="h-4 w-4 text-gray-500" />
              <span>Week 1 Requirements</span>
            </div>
            <ul className="space-y-2 text-xs text-gray-600 leading-normal">
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-indigo-600 shrink-0 mt-0.5" />
                <span><strong>Detailed Report</strong> structured with proper mathematical metrics and risk management.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-indigo-600 shrink-0 mt-0.5" />
                <span><strong>Python Libraries</strong> integration outline (Pandas, NumPy, Matplotlib).</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-indigo-600 shrink-0 mt-0.5" />
                <span><strong>Expected Visualization</strong> mock graphs modeling cash trajectories.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-indigo-600 shrink-0 mt-0.5" />
                <span><strong>Executive Summary</strong> capturing granular stakeholder recommendations.</span>
              </li>
            </ul>
          </div>

          {/* CFO Action Banner */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 text-white space-y-3 shadow-sm">
            <div className="flex items-center gap-1.5 text-xs font-bold text-indigo-400 uppercase tracking-wider font-mono">
              <Sparkles className="h-4 w-4" />
              <span>AI CFO Review Engine</span>
            </div>
            <p className="text-slate-300 text-xs leading-relaxed">
              Audit the strategy draft with server-side Gemini. Receive specialized metric recommendations and custom Python equations.
            </p>
            <button
              onClick={triggerAIReview}
              disabled={isAIReviewing}
              className="w-full flex items-center justify-center gap-2 px-4 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-800 disabled:text-slate-500 rounded-lg transition"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isAIReviewing ? "animate-spin" : ""}`} />
              {isAIReviewing ? "Processing Audit..." : "Evaluate Draft Now"}
            </button>
          </div>
        </div>

        {/* Column 2: Document Builder Workspace (5 Cols on Desktop) */}
        <div className="lg:col-span-5 flex flex-col">
          <StrategyEditor 
            report={report} 
            onUpdateReport={setReport} 
            onTriggerAIReview={triggerAIReview}
            isAIReviewing={isAIReviewing}
          />
        </div>

        {/* Column 3: Simulator & AI Critique Outputs (4 Cols on Desktop) */}
        <div className="lg:col-span-4 space-y-6 flex flex-col justify-start">
          {/* Matplotlib Interactive Simulation */}
          <PythonSimulator sectorId={activeSector.id} metrics={report.metrics} />

          {/* AI CFO Review Console */}
          <AIReviewer 
            reviewData={reviewData} 
            isLoading={isAIReviewing} 
            onApplyFeedback={applyAIFeedback}
            error={aiError}
          />
        </div>

      </main>

      {/* Footer bar */}
      <footer className="bg-white border-t border-gray-200 mt-12 py-6 text-center text-xs text-gray-500 font-mono">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <span>Financial Data Analysis Strategy Platform &copy; 2026</span>
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1"><FileCheck className="h-3.5 w-3.5 text-emerald-600" /> MS Word Compliant Exporter</span>
            <span className="flex items-center gap-1"><Cpu className="h-3.5 w-3.5 text-indigo-600" /> Dynamic Vector Engine</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
